# MUST HAVE a unique name for workflow_run trigger in the next step
name: R CMD Check CRAN

on:
  push:
    branches:
      - r-package-build

permissions:
  contents: read # Only needs read access

jobs:
  r-cmd-check:
    runs-on: ubuntu-latest
    env:
      # Prevent interactive prompts during checks
      _R_CHECK_CRAN_INCOMING_: FALSE
      # Speed up builds by setting parallel make jobs
      MAKEFLAGS: "-j${{ runner.N_CPU }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: r-package-build

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Set up Pandoc # Often needed for vignettes
        uses: r-lib/actions/setup-pandoc@v2

      # Optional: Install system dependencies if your package needs them
      # - name: Install system dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies (including Rcpp if needed by check)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rcpp # Ensure Rcpp is available if DESCRIPTION lists it
            any::rcmdcheck
            any::sessioninfo
          needs: check # Installs Imports, Depends, Suggests, Enhances

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          args: '--as-cran --no-manual' # Strict CRAN check, skip building PDF manual (faster)
          # Optional: Specify where check results should be uploaded
          # upload-snapshots: true

      # This step is useful for debugging if check fails
      - name: Show session info
        if: failure()
        run: |
          options(width = 200)
          sessioninfo::session_info()
        shell: Rscript {0}